# Generated by Django 5.1.7 on 2025-04-12 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 12, 11, 42, 20, 954721)
            ),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="address",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
