# Generated by Django 5.1.7 on 2025-04-13 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_orderstatus_alter_products_created_at_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("returned", "Returned"),
                ],
                default="processing",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 13, 22, 31, 22, 504747)
            ),
        ),
        migrations.DeleteModel(
            name="OrderStatus",
        ),
    ]
