# Generated by Django 5.1.7 on 2025-04-14 05:20

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_order_status_alter_products_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 14, 11, 19, 57, 57768)
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
